events {
    worker_connections 4096;
}

http {
    access_log off;
    keepalive_requests 100000;
    resolver 127.0.0.11 valid=5s ipv6=off;

    upstream rate_limiter {
        zone rate_limiter 64k;
        least_conn;
        server api1:8000;
        server api2:8000;
        server api3:8000;
        keepalive 128;
    }

    server {
        listen 80;
        client_max_body_size 1m;

        location / {
            proxy_pass http://rate_limiter;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection "";
            proxy_connect_timeout 2s;
            proxy_read_timeout 30s;
        }
    }
}
